game.AddParticles( "particles/Thunderlord_FX2.pcf" )
game.AddParticles( "particles/tracer_fx.pcf" )
game.AddParticles( "particles/ThunderlordMuzzle.pcf" )
game.AddParticles( "particles/lightning.pcf" )
PrecacheParticleSystem( "storm_muzzle" )
PrecacheParticleSystem( "storm_muzzle_cheap" )
PrecacheParticleSystem( "astra_hit" )
PrecacheParticleSystem( "thunderlord_lightning" )
PrecacheParticleSystem( "thunderlord_tracer" )		

PrecacheParticleSystem( "vp_binary_muzzle" )
PrecacheParticleSystem( "vp_binary_tracer" )
PrecacheParticleSystem( "vp_dissolve" )
PrecacheParticleSystem( "vp_dissolve_cheap" )		
PrecacheParticleSystem( "aquamarine_tracer" )