hook.Add( "PopulateToolMenu", "CSOSettingsMenu", function()
	spawnmenu.AddToolMenuOption( "Options", "TFA SWEP Base Settings", "CSO_P4", "CSO: Part 4", "", "", function( panel )
		panel:ClearControls()
		panel:AddControl("Label", { Text = "Dual Beretta Windrider's right-click damage." } )
		panel:NumSlider( "Default is 12.", "sv_tfa_cso_dmg_windrider_rb", 1, 100 )
		panel:AddControl("Label", { Text = "Dual Beretta Gunslinger's right-click damage." } )
		panel:NumSlider( "Default is 15.", "sv_tfa_cso_dmg_gunslinger_rb", 1, 100 )
		panel:AddControl("Label", { Text = "Dual Beretta Gunslinger GS's right-click damage." } )
		panel:NumSlider( "Default is 18.", "sv_tfa_cso_dmg_gunslinger_gs_rb", 1, 100 )
		panel:AddControl("Label", { Text = "Can Dual Beretta Gunslingers deal right-click damage to players?" } )
		panel:CheckBox( "Default is off.", "sv_tfa_cso_dmg_gunslingers_player", 0, 1 )
		panel:AddControl("Label", { Text = "Will the Trinity Grenades do special things to players (detect, ignite)?" } )
		panel:CheckBox( "Default is off.", "sv_tfa_cso_dmg_trinity_detect_player", 0, 1 )
	end )
end )